package com.example.taskomanagement.utils

sealed class Screen(val routes: String) {
    data object LandingPageScreen: Screen("LandingPageScreen")
    data object LoginScreen: Screen("LoginScreen")
    data object RegisterScreen: Screen("RegisterScreen")
    data object RegisterSuccessScreen: Screen("RegisterSuccessScreen")
    data object HomeScreen: Screen("HomeScreen")
    data object ProjectsScreen: Screen("ProjectsScreen")
    data object MessageScreen: Screen("MessageScreen")
    data object TeamsScreen: Screen("TeamsScreen")
    data object ProfileScreen: Screen("ProfileScreen")
    data object MainScreen: Screen("MainScreen")
    data object AuthenticationScreen: Screen("AuthenticationScreen")
    data object TeamDetailScreen: Screen("TeamDetailScreen/{teamId}")
    data object ProjectDetailScreen: Screen("ProjectDetailScreen/{projectId}")
    data object TaskScreen: Screen("TaskScreen")
    data object TaskDetailScreen: Screen("TaskDetailScreen/{taskId}")
    data object TeamInputScreen: Screen("TeamInputScreen")
    data object ProjectChooseTeamScreen: Screen("ProjectChooseTeamScreen")
    data object ProjectInputScreen: Screen("ProjectInputScreen/{teamId}")
    data object TaskInputScreen: Screen("TaskInputScreen/{projectId}")
    data object MembersScreen: Screen("MembersScreen/{teamId}")
    data object ChatScreen: Screen("ChatScreen/{memberId}")
    data object MemberInputScreen: Screen("MemberInputScreen/{teamId}")
}